/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: d87fdb2c6b796ec0edda9fbab046cf90)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env {
		AI: Ai;
		ASSETS: Fetcher;
		BROWSER: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
